a = input('Digite algo:')
print('O tipo primitivo desse valor é?', type(a))
print('Só tem espaços? ', a.isspace())
print('É um numero? ', a.isnumeric())
print('É alfabetico? ', a.isalpha())
print('É alfanumerico? ', a.isalnum())
print('Esta em Maiusculas? ', a.isupper())
print('Esta em Minusluas? ', a.islower())
print('Esta Capitalizada? ', a.istitle())